# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0003_auto_20161011_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_list.Movie'),
        ),
    ]
