# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0004_person_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='name',
        ),
    ]
