# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0008_auto_20161011_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
