OMDB_MODEL_MAPPING = {
    'Actors': 'actors',
    'Awards': '',
    'Country': 'country',
    'Director': 'director',
    'Genre': 'genre',
    'Language': '',
    'Metascore': 'metascore',
    'Plot': 'description',
    'Poster': 'icon',
    'Rated': '',
    'Released': '',
    'Response': '',
    'Runtime': '',
    'Title': 'title',
    'Type': '',
    'Writer': '',
    'Year': 'year',
    'imdbID': 'imdb_url',
    'imdbRating': 'imdb_rating',
    'imdbVotes': '',
}