OMDB_MODEL_MAPPING = {
    'Actors': '',
    'Awards': '',
    'Country': '',
    'Director': '',
    'Genre': '',
    'Language': '',
    'Metascore': '',
    'Plot': 'description',
    'Poster': '',
    'Rated': '',
    'Released': '',
    'Response': '',
    'Runtime': '',
    'Title': 'title',
    'Type': '',
    'Writer': '',
    'Year': '',
    'imdbID': '',
    'imdbRating': '',
    'imdbVotes': '',
}